---
title: "epitools: Relative Risks and Odds Ratios"
author: "Amanda Ng"

format:
  live-html:
    toc: true
    number-sections: false
  
engine: knitr

resources:
  - data

webr:
  packages:
    - tidyverse
    - grid
    - ggplot2

live:
  show-hints: true
  show-solutions: true
---

{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}

# Relative Risks and Odds Ratios

We can also compute *relative risks* (RR) and *odds ratios* (OR) to compare risk and odds of individuals falling within certain groups (income, education, etc.) also using cannabis at certain frequencies. Unfortunately, there are no functions in base R (or `tidyverse`) to compute RR and OR. So, we need to install and load another R package: `epitools`.

``` r
#install.packages("epitools")
library(epitools)
```

```{webr}
#| include: false
#install.packages("epitools")
library(epitools)
cannabis_data <- read.csv("data/cannabis_data.csv")
```

To calculate the OR and RR, we first need to collapse our income and frequency groups into two binary outcomes respectively, and determine what constitutes to lower/ higher income and lower/ higher frequency.

```{webr}
cannabis_data <- cannabis_data %>%
  # Transform numerical back to categorical representation
  mutate(recreational_use_frequency = factor(use_freq_rec, 
                       levels = 1:7,
                       labels = c("< 1 day per month", "1 day per month", "2-3 days a month", 
                                 "1-2 days a week", "3-4 days a week", "5-6 days a week", "Daily"))) %>% 
  mutate(annual_income = factor(income_recode, 
                         levels = 1:4,
                         labels = c("<$50k", "$50K to <$100K", 
                                    "$100K to <$150K", ">150K "))) %>%
  # Collapse into binary variables  
  mutate(cannabis_use_binary = case_when(
    use_freq_rec %in% 1:3 ~ "Infrequent Usage", 
    use_freq_rec %in% 4:7 ~ "Frequent Usage",    
    TRUE ~ NA_character_
  )) %>%

  mutate(income_binary = case_when(
    income_recode %in% 1:2 ~ "Lower Income", 
    income_recode %in% 3:4 ~ "Higher Income",  
    TRUE ~ NA_character_
  ))

```

Now we can perform our RR and OR calculations using the package function `epitab()`:

```{webr}
# RR
epitab(table(cannabis_data$income_binary, cannabis_data$cannabis_use_binary), 
       method = "riskratio")$tab
```

```{webr}
# OR
epitab(table(cannabis_data$income_binary, cannabis_data$cannabis_use_binary), 
       method = "oddsratio")$tab
```

The fifth column is labeled either *riskratio* or *oddsratio*, depending on which method you specify in the function. `$tab` at the end of the code is used to display the results in a table format. You will learn what the columns to the right of it later in the course.

Based on this output and these data, the odds of high frequency cannabis usage for those classified as being lower income is 1.56 times the odds those classified as being high income. And, the risk of high frequency cannabis usage for those classified as being higher income is roughly 17% lower than those in the low income group. In conclusion, lower income is associated with more frequent cannabis usage for recreational purposes.

# Coding Exercise

You give it a try! Create appropriate summaries to explore the association between high cannabis usage frequency and education level. For simplicity, the `cannabis_data` has been cleaned for you with additional binary variables `cannabis_use_binary` (corresponding to `recreational_use_frequency`) and `education_binary` (corresponding to `education`).

```{webr}
#| setup: true
#| exercise: ex_1
cannabis_data <- read.csv("cannabis_data.csv")
cannabis_data <- cannabis_data %>% 
  select(prov, education3, income_recode, community_size, use_freq_rec) %>%
  filter(if_all(everything(), ~ . != -7)) %>%
  filter(if_all(everything(), ~ . != -8))
cannabis_data <- cannabis_data %>%
  mutate(recreational_use_frequency = factor(use_freq_rec, 
                       levels = 1:7,
                       labels = c("< 1 day per month", "1 day per month", "2-3 days a month", 
                                 "1-2 days a week", "3-4 days a week", "5-6 days a week", "Daily"))) %>% 
  mutate(annual_income = factor(income_recode, 
                         levels = 1:4,
                         labels = c("<$50k", "$50K to <$100K", 
                                    "$100K to <$150K", ">150K "))) %>%
    mutate(cannabis_use_binary = case_when(
    use_freq_rec %in% 1:3 ~ "Infrequent Usage", 
    use_freq_rec %in% 4:7 ~ "Frequent Usage",    
    TRUE ~ NA_character_
  )) %>%
  mutate(income_binary = case_when(
    income_recode %in% 1:2 ~ "Lower Income", 
    income_recode %in% 3:4 ~ "Higher Income",  
    TRUE ~ NA_character_
  )) %>%
  mutate(education = factor(education3, 
                         levels = 1:3,
                         labels = c("High School or Less", "Trades or non-university diploma", "Bachelor's Degree or Higher"))) %>%
  mutate(education_binary = case_when(
    education3 %in% 1:2 ~ "High School/Trades", 
    education3 == 3 ~ "Bachelors or Higher",  
    TRUE ~ NA_character_
  ))
```

:::::: panel-tabset
## Exercise

```{webr}
#| exercise: ex_1
#| min-lines: 10



```

## Hints

::: {.hint exercise="ex_1"}
What type of variables are they?
:::

::: {.hint exercise="ex_1"}
Review the code for cannabis use frequency and income.

Does any of those summaries that work in this situation?
:::

## Solution

::: {.solution exercise="ex_1"}
Here are several options:

``` r
# Stacked barplot
barplot(table(cannabis_data$education, cannabis_data$recreational_use_frequency), 
        legend.text = TRUE, 
        xlab = "Highest Level of Education")

# Mosaic plot
mosaicplot(table(cannabis_data$education, cannabis_data$recreational_use_frequency), 
        legend.text = TRUE, 
        xlab = "Highest Level of Education", ylab="Recreational Cannabis Usage Frequency")

# Frequency table
table(cannabis_data$education, cannabis_data$recreational_use_frequency)

# Proportional table
prop.table(table(cannabis_data$education, cannabis_data$recreational_use_frequency),margin=2)

# RR
epitab(table(cannabis_data$education_binary, cannabis_data$cannabis_use_binary), method="riskratio")$tab

# OR
epitab(table(cannabis_data$education_binary, cannabis_data$cannabis_use_binary), method="oddsratio")$tab
```
:::
::::::
