---
title: "ggplot2"
author: "Amanda Ng"

format:
  live-html:
    toc: true
    number-sections: false
  
engine: knitr

resources:
  - data

webr:
  packages:
    - tidyverse
    - grid
    - ggplot2

live:
  show-hints: true
  show-solutions: true
---

{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}

# Visualizing Data with ggplot2

In the following sections, we will produce plots using the **`ggplot2`** package, a *grammar of graphics* package which is also part of the **`tidyverse`** package.

The basic syntax of `ggplot2 in R` involves building plots step by step by adding layers with +. The general syntax is

```{r, eval=FALSE, echo =TRUE}

ggplot(data , mapping = aes(...)) +
  <GEOM_FUNCTION>(aes(...), ...) +
  <OTHER_LAYERS> 

```

Any plot produced using `ggplot()` requires the following main components:

1.  `ggplot(data, aes(...))`

-   `data` is *data frame* that contains the data (in tidy data format) to plot,
-   `aes():` *aesthetics* mappings (which variables are mapped to the x-axis, y-axis, color, size, shape, etc.).

2.  `+ geom_*()` sepcifies the *geometry* that defines how the plot will be drawn (e.g., histogram, scatterplot, etc.).
3.  Optional layer: `scale_x_continuous`, `scale_y_continuous` to customize axes (ticks, names, scale)
4.  Optional layer: `labs(x = ..., y = ..., subtitle = ..., title = ...)` to customize the labels for the axes and plot titles
5.  Optional layer: `ggplot` themes: e.g., `theme_classic()`, `theme_bw()`, `theme_minimal()`, `theme_dark()`, `theme_light()`. Complete list [here](https://ggplot2.tidyverse.org/reference/ggtheme.html).

Examples of geom layers are:

`geom_histogram()`: represents numeric (continuous) data as a histogram

`geom_line()`: represents data as lines joining data points (e.g., line graphs)

`geom_bar()` : represents discrete data as a bar chart

`geom_point()`: represents data as points (e.g., scatter plots)

There are many ways to customize your plots by building on the basic code. As you gain more experience with R, you will discover that there are multiple ways to do things in R, including data visualizations. But, we are focussing on **`ggplot2`** here since it is a powerful package you can use to produce impressive (and effective!) visualizations.

# Numerical Variable

Let's begin with the `pfas_data` data:

```{webr}
#| include: false
pfas_data <- read.csv("data/pfas_data.csv")
total_pfas_data <- pfas_data %>%
  filter(Analyte == "Total PFAS") 
pfas_data_mean <- pfas_data %>%
  filter(Analyte == "Total PFAS") %>%
  group_by(State) %>% 
  summarise(mean_ppt = mean(Value..PPT.))
```

```{webr}
head(pfas_data)
```

Suppose we are interested in the distribution of total PFAS levels for the 2023 EWG/EPA PFAS data. 

**QUESTION**

Which of the following plots would be appropriate to visualize the distribution of total PFAS measurements? Select all that apply.

- A. Histogram
- B. Barplot
- C. Dotplot
- D. Boxplot
- E. Scatterplot

```{webr}
#| exercise: ex_1
answer = c()   # Enter all correct options in order: e.g., c("A", "C")

# Do not edit this
answer 
```

```{webr}
#| exercise: ex_1
#| check: true

#| exercise: ex_1
#| check: true

correct_answers <- c("A", "C", "D")   # update as needed

# Messages for specific wrong choices
msg_B <- "A barplot would not be appropriate here. We use barplots to summarize categorical variables. Is PFAS (ppt) categorical? Please try again."
msg_E <- "A scatterplot would not be appropriate. Scatterplots are for two quantitative variables. Here we have one variable (PFAS levels). Please try again."

# If nothing selected
if (length(.result) == 0) {
  list(
    correct = FALSE,
    message = "Please select at least one option."
  )

# If they selected B (barplot)
} else if ("B" %in% .result) {
  list(
    correct = FALSE,
    message = msg_B
  )

# If they selected E (scatterplot)
} else if ("E" %in% .result) {
  list(
    correct = FALSE,
    message = msg_E
  )

# If they selected all and only the correct answers
} else if (setequal(.result, correct_answers)) {
  list(
    correct = TRUE,
    message = "Correct! PFAS (ppt) levels are quantitative measurements so the plots you selected are appropriate summaries of this distribution!"
  )

# Any other incorrect combination
} else {
  list(
    correct = FALSE,
    message = paste0(
      "Not quite. The correct answers are: ",
      paste(correct_answers, collapse = ", "),
      ". You selected: ",
      paste(.result, collapse = ", "),
      "."
    )
  )
}

```

## *Histograms* 

Histograms are used to show the frequency distribution of *numerical* data within a dataset. They are useful for understanding the spread, skewness, and the presence of any outliers in the data. We use `geom_histogram` to create histograms. 

Try running the following code to create a histogram of PFAS levels on the cleaned dataset `total_pfas_data`, in which PFAS levels are stored in `Value..PPT.` variable.

```{webr}
#| warning: false
# Histogram of total_pfas_data$`Value..PPT.`
total_pfas_data %>% 
  ggplot(aes(x = Value..PPT.)) +
  geom_histogram(binwidth = 10) + # Bin width set as 10
  xlim(0, 100) # x axis is displayed from 0 to 100
```

You can also change the features of the histogram within `geom_histogram`:

  - bin width using the `binwidth` argument 
  - bar fill colours using the `fill` argument 
  - outline colour of the bars using the `colour` argument

For example:

```{webr}
#| warning: false
#  Changing binwidth/fill/colour
total_pfas_data %>% 
  ggplot(aes(x = Value..PPT.)) +
  geom_histogram(binwidth = 8, fill = "blue", colour = "red") + 
  xlim(0, 100)
```

Give it a try!

## *Boxplots* 


*Boxplots* show the distribution of numerial data through statistical means rather than as frequency values. The box contains the middle 50% of the data, the line in the middle of the box represents the median, while the whiskers extend to the minimum and maximum values. We use `geom_boxplot` to create boxplots. 

Try running the following code to create a boxplot of mean PFAS levels across different states on the cleaned dataset `pfas_data_mean`, in which state-specific mean PFAS levels are stored in `mean_ppt` variable:

```{webr}
#| warning: false
#| message: false
# Boxplot of pfas_data_mean$mean_ppt
pfas_data_mean %>% 
  ggplot(aes(y = mean_ppt)) +
  geom_boxplot()

```



Note that to create this boxplot, PFAS levels were specified as y rather than x in `aes()` to maintain consistency with the boxplot format in the course. Try changing y to x in `aes()` and rerunning the code above to see what happens. Sometimes you encounter boxplots that look like this as well.

## *Dotplots* 

*Dotplots* also show the distribution of the data, with each observation represented as a dot. Hence, dotplots are best used when the dataset is small. We use `geom_dotplot` to create boxplots and dotplots. 

Try running the following code to create a dotplot of mean PFAS levels across different states on the cleaned dataset `pfas_data_mean`, in which state-specific mean PFAS levels are stored in `mean_ppt` variable:

```{webr}
#| warning: false
#| message: false
# Dotplot of pfas_data_mean$mean_ppt
pfas_data_mean %>% 
  ggplot(aes(x = mean_ppt)) +
  geom_dotplot(dotsize = 0.8) # Try changing dotsize

```

# Categorical Data

Let's begin with the `cannabis_data` data:

```{webr}
#| include: false
cannabis_data <- read.csv("data/cannabis_data.csv")
```

```{webr}
head(cannabis_data)
```

Suppose we are interested in the location distribution of the cannabis_data survey respondents: 

**QUESTION**

Which of the following plots would be appropriate to visualize how the survey respondents are distributed across provinces?

- A. Boxplot
- B. Scatterplot
- C. Histogram
- D. Barplot

```{webr}
#| exercise: ex_2
answer = # Enter one of the followings: "A", "B", "C"

# Do not edit this
answer 
```

```{webr}
#| exercise: ex_2
#| check: true

if (.result == "D") {
  list(
    correct = TRUE,
    message = "Yes! prov is a categorical variable so a barplot is an appropriate summary of this distribution."
  )
} else if (.result == "A") {
  list(
    correct = FALSE,
    message = "A boxplot would not be appropriate. Boxplots are appropriate summaries of distributions of quantitative variables. province is a categorical variable. Please try again."
  )
} else if (.result == "B") {
  list(
    correct = FALSE,
    message = "A scatterplot would not be appropriate. Scatterplots are appropriate when you have two quantative variables and are interested in their association. Here we have one categorical variable - province. Please try again."
  )
} else if (.result == "C") {
  list(
    correct = FALSE,
    message = "A histogram would not be appropriate. Histograms are appropriate summaries of distributions of quantitative variables. Province is a categorical variable. Please try again."
  )
}else {
  list(
    correct = FALSE,
    message = "Please select an answer."
  )
}
```

## *Barplots* 

Barplots are a type of data visualization useful for comparing between groups and showing the relationship between a numerical and a categorical variable. They are highly useful for visualizing survey data! 

Notice that the data type for the `prov` column is integer in the dataframe.

```{webr}
class(cannabis_data$prov)
```

However, they are the coded representation of each province, instead of meaningful numerical values. Thus, we can use a function we learned in module 1 (i.e.,mutate) to convert the survey responses back into categories to generate a bar plot.

We use `geom_bar` to create bar plots. Run the following code to create a bar plot of the distribution of the provinces individuals in this `cannabis_data` survey fall into. `factor()` is used to convert the survey integer responses into more meaningful descriptions:

```{webr}
#| setup: true
#| exercise: ex_3
library(tidyverse)
cannabis_data <- read.csv("data/cannabis_data.csv")
cannabis_data <- cannabis_data %>% 
  select(prov, education3, income_recode, community_size, use_freq_rec) %>%
  filter(if_all(everything(), ~ . != -7)) %>%
  filter(if_all(everything(), ~ . != -8))
```

:::: {.panel-tabset}
## Exercise
```{webr}
#| exercise: ex_3
#| warning: false
# Barplot of number of individuals in each province
cannabis_data %>% 
  mutate(province = factor(prov, # the variable we are trying to transform
                       levels = 1:11,     # original representation 
                       labels = c("AB", "BC", "MB",      # the corresponding transformation, e.g. 1 -> AB
                                 "NB", "NL", "NS", "ON", 
                                 "PE", "QC", "SK", "Territories"))) %>% 
  ggplot(aes(x = province)) +
  geom_bar()

```

## Note 1
To change the y axis to percent instead of the default of count, you can add the code  `+ scale_y_continuous(name="Percent",labels = scales::percent)` after `geom_bar()`. Give it a try!

::: { .hint exercise="ex_3"}
::: { .callout-note collapse="false"}

```r
# Barplot of Percentage of individuals in each province
cannabis_data %>% 
  mutate(province = factor(prov, # the variable we are trying to transform
                       levels = 1:11,     # original representation 
                       labels = c("AB", "BC", "MB",      # the corresponding transformation, e.g. 1 -> AB
                                 "NB", "NL", "NS", "ON", 
                                 "PE", "QC", "SK", "Territories"))) %>% 
  ggplot(aes(x = province)) +
  geom_bar() + 
  scale_y_continuous(name="Percent",labels = scales::percent)

```
:::
:::

## Note 2
You can also change the features of the bar graph within `geom_bar` similarly as histogram. Give it a try! 

::: { .hint exercise="ex_3"}
::: { .callout-note collapse="false"}
```r
# Example of changing colours
cannabis_data %>% 
  mutate(province = factor(prov, # the variable we are trying to transform
                       levels = 1:11,     # original representation 
                       labels = c("AB", "BC", "MB",      # the corresponding transformation, e.g. 1 -> AB
                                 "NB", "NL", "NS", "ON", 
                                 "PE", "QC", "SK", "Territories"))) %>% 
  ggplot(aes(x = province)) +
  geom_bar(fill = "#56C8FC" , colour = 'blue') 

```
:::
:::
::::


# Multiple Variables

## Using *facet_wrap* to show visualizations by group 

Suppose we were interested in comparing cannabis usage frequency for those across different income levels. We can produce visualizions comparing the distributions of recreational cannabis usage frequencies for these groups using  **`facet_wrap`**. Similar to the previous section, we first have to transform `recreational_use_frequency` and `income_recode` variables from numerical representation back to their corresponding string representation.

```{webr}
# Create separate bar plots by income level
cannabis_data %>%
  
  # Transform use_freq_rec variable back to string representation
  mutate(recreational_use_frequency = factor(use_freq_rec, 
                       levels = 1:7,
                       labels = c("< 1 day per month", "1 day per month", "2-3 days a month", "1-2 days a week", "3-4 days a week", "5-6 days a week", "Daily"))) %>% 
  
  # Transform income_recode variable back to string representation
  mutate(annual_income = factor(income_recode, 
                         levels = 1:4,
                         labels = c("<$50k", "$50K to <$100K", 
                                    "$100K to <$150K", ">150K "))) %>%
  
  # Create bar plot to count recreational_use_frequency
  ggplot(aes(x = recreational_use_frequency)) +
  geom_bar() + 
  
  # Grouped by annual_income
  facet_wrap(~annual_income)

```

## Using *boxplots* to represent multivariable data

Boxplots can also be used to represent comparisons among multiple groups. Let's say we are interested in looking at the different concentrations of PFAS analytes vary in the state of New Jersey: 

```{webr}
# Boxplots of PFAS concentration for different analytes in NJ
pfas_data %>%
  filter(State == "NJ") %>%
  group_by(Analyte) %>%
  ggplot(aes(x = Analyte, y = Value..PPT.)) + 
  geom_boxplot()
  
```


## *Scatterplots* 

Scatter plots are data visualizations used to look at the relationship between two quantitative variables. For example, we can use it to explore the association between environmental PFAS concentrations and birth weight. We use `geom_point` to create scatterplots. We will use the joined `pfas_births` dataset:

```{webr}
#| include: false
birth_data <- read.csv("data/birth_data.csv")
birth_data <- birth_data %>% rename(State = State.Abbreviation)
pfas_births <- left_join(pfas_data_mean, birth_data, by = "State")
```

```{webr}
# Scatter plot of mean PFAS vs average birth weight
pfas_births %>%
  
  # Remove observations with missing calues in these variables
  drop_na(mean_ppt, Average.Birth.Weight..grams.) %>%
  
  # Create scatter plot 
  ggplot(aes(x = mean_ppt, y = Average.Birth.Weight..grams.)) +
  geom_point() +
  
  # Set the plot theme to has minimal features
  theme_minimal() +
  
  # Give meaningful axis labels
  labs(
    x = "Mean PFAS (ppt)",
    y = "Average Birth Weight (grams)")
  
```

From this, we can see a moderate negative association in our data, suggesting that higher PFAS exposure may be associated with lower birth weights. Statistical tests can be used to determine whether the relationship between the variables of interest is greater than what we would expect to see by chance. However, performing statistical analysis is beyond the scope of this tutorial. If you would like to draw more attention to the association, you can create a line of best fit based on the data using `geom_smooth(method = "lm") `: 

```{webr}
pfas_births %>% 
  ggplot(aes(x = mean_ppt, y = Average.Birth.Weight..grams.)) + 
  geom_point() + 
  # Include best fit line
  geom_smooth(method = "lm", se = TRUE) + #se shows the standard error of the model
  labs(x = "Mean PFAS Exposure by State (ppt)", y = "Average Birth Weight (g)") +
  theme_minimal()

```


# Coding Exercise

Now it's time to apply the concepts we've gone over!

Using `cannabis_data`, write a code to produce a visualization that displays the distribution of cannabis recreational use frequency across different education levels.

```{webr}
#| setup: true
#| exercise: 
#|   - ex_4
#|   - ex_5
library(tidyverse)
cannabis_data <- read.csv("data/cannabis_data.csv")

cannabis_data <- cannabis_data %>% 
  select(prov, education3, income_recode, community_size, use_freq_rec) %>%
  filter(if_all(everything(), ~ . != -7)) %>%
  filter(if_all(everything(), ~ . != -8))

cannabis_data <- cannabis_data %>%
  mutate(recreational_use_frequency = factor(use_freq_rec, 
                       levels = 1:7,
                       labels = c("< 1 day per month", "1 day per month", "2-3 days a month", "1-2 days a week", "3-4 days a week", "5-6 days a week", "Daily"))) %>% 
  mutate(education = factor(education3, 
                         levels = 1:3,
                         labels = c("High School or Less", "Trades or non-university diploma", "Bachelor's Degree or Higher")))
```

:::: {.panel-tabset}

## Exercise

```{webr}
#| exercise: ex_4
#| min-lines: 6
cannabis_data

```

## Hints
::: { .hint exercise="ex_4"}
What type of data are recreational use frequency and education level?
:::

::: { .hint exercise="ex_4"}
facet_wrap() can be used to group data
:::

## Solution

::: { .solution exercise="ex_4" }
```r
cannabis_data %>%
   ggplot(aes(x = recreational_use_frequency)) +
   geom_bar() + 
   facet_wrap(~education)
```
:::
::::

Using the `pfas_births` data, create a data visulization of the relationship between PFAS exposure `mean_ppt` and fertility rate `Fertility.Rate`. Make sure to include meaningful axis labels!

:::: {.panel-tabset}

## Exercise

```{webr}
#| exercise: ex_5
#| min-lines: 8
pfas_births%>%
  drop_na(mean_ppt, Fertility.Rate)


```

## Solution

::: { .solution exercise="ex_5" }

```r
pfas_births %>%
  drop_na(mean_ppt, Fertility.Rate) %>%
  ggplot(aes(x = mean_ppt, y = Fertility.Rate)) +
  geom_point() +
  theme_minimal() +
  labs(
    x = "Mean PFAS (ppt)",
    y = "Fertility Rate (per 1000 female population)")
```
:::
::::